### ISSUE TITLE
Cleanup FAQ

### ISSUE THREAD

**Issue by bdha** [illumos/docs#14]
https://illumos.github.io/docs/about/faq/

Remove any old/irrelevant content. What's missing?

Examples:

https://www.openbsd.org/faq/
https://www.freebsd.org/doc/en_US.ISO8859-1/books/faq/

**Comment by jclulow** [comment]
Removed most of the references to Oracle as a potential upstream.  Clarified that we're in no way compatible with Solaris 11, etc.
