### ISSUE TITLE
Dead link on The Quality Death Spiral

### ISSUE THREAD

**Issue by MrOffline77** [illumos/docs#53]
On the page `https://illumos.org/docs/contributing/qds/` is a link to a hub.opensolaris (down below). This is a dead link since this domain is not resolving anymore. 
Maybe we can provide a copy ourself on the documentation (if permissions are ok) or refer to another link where this is hosted now.

**Comment by jclulow** [comment]
It's a reference link, which intends to show where we got it from.  I don't believe there's a more canonical copy that exists today.

We could link to a copy in the Internet archive instead, though; e.g., https://web.archive.org/web/20110104044942/http://hub.opensolaris.org/bin/view/Community+Group+on/qual_death_spiral

**Comment by jclulow** [comment]
Thanks for the report!  I've fixed this on the site.
