### ISSUE TITLE
Dead link to logos

### ISSUE THREAD

**Issue by wiedi** [illumos/docs#66]
On https://www.illumos.org/docs/about/logo/ the link to download the "Zip of all logos" no longer works.
Seems like it was part of the older smartos wiki.

Luckily archive.org still has a copy at https://web.archive.org/web/20161118032732/https://wiki.smartos.org/download/attachments/753667/illumos_logos.zip

Do we have a place for such things? Should this live in this repo or somewhere else?

**Comment by gdamore** [comment]
I don't think we do, and I'd rather not publish it in that format.  The versions of the logo that are directly linked are the ones to use.
