### ISSUE TITLE
Dead link on the history page

### ISSUE THREAD

**Issue by domag02** [illumos/docs#84]
There is a dead link on the [https://illumos.org/docs/about/history/](https://illumos.org/docs/about/history/) page:
`[silently closed the gate](http://sstallion.blogspot.com.au/2010/08/opensolaris-is-dead.html)`: this blog is not available anymore, but can be found on archive.org: [https://web.archive.org/web/20170904093634/http://sstallion.blogspot.nl/2010/08/opensolaris-is-dead.html](https://web.archive.org/web/20170904093634/http://sstallion.blogspot.nl/2010/08/opensolaris-is-dead.html)

**Comment by jclulow** [comment]
Thanks!  I've sorted this out now.
